//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Registration
    {
        public int ID { get; set; }
        public int bookingNumber { get; set; }
        public System.DateTime CustomerBirthDate { get; set; }
        public string VehicleType { get; set; }
        public System.DateTime rentStartDate { get; set; }
        public decimal CurrentMilageKm { get; set; }
        public Nullable<System.DateTime> rentEndDate { get; set; }
    }
}
